# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nishant Nimbare
email: nishantnimbare@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineering at Accolite Digital | Technical Consultant at Morgan Stanley.
twitter_username: nishantnimbare
github_username: nishant-nimbare
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
style: darks

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-github-metadata
  - jekyll-octicons


analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-173588793-1"
    anonymize_ip: false # default

author:
  name   : "Nishant Nimbare"
  avatar : "/assets/images/panda.jpeg"
  bio    : "SWE @ Accolite | DJSCE."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:nishantnimbare@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://www.github.com/nishant-nimbare"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nishant-nimbare/"  
    - label: "LeetCode"
      icon: "fab fa-fw fa-code"
      url: "https://leetcode.com/nishant-nimbare/"
    # - label: "GitLab"
    #   icon: "fab fa-fw fa-gitlab"
    #   url: "https://gitlab.com/nishant-nimbare"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/nishantnimbare/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nishantnimbare"

      
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:nishantnimbare@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "http://www.github.com/nishant-nimbare"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nishant-nimbare/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/



projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  exclude:
    archived: false
    forks: false
    projects:
      - signalling-server
    # - repo-name
